### ISSUE TITLE
GM Only disables for GM only

### ISSUE THREAD

**Issue by Naroek56** [ElfFriend-DnD/foundryvtt-confetti#5]
System information:
Windows 10
Foundry 0.7.9
System: Old-School Essentials 1.1.4, Quest 1.11.1
Confetti 1.0.2

Issue:
When ticking the box "GM Only" the Confetti tab disappears for the GM. It stays for any logged in players. Un-ticking it only works after a world restart.

**Comment by akrigline** [comment]
@Naroek56 what version of confetti are you using? I thought this was fixed with 1.0.2

**Comment by Naroek56** [comment]
Sorry, accidentally wrote polyglot, I added the Confetti version.

**Comment by akrigline** [comment]
Gotchya, dang. I'm not sure I'm going to get to this anytime soon but thanks for the report!

**Comment by akrigline** [comment]
I can't reproduce this, can you double check?

Changing the setting does require a reload from any logged in players, but that's acceptable to me.
